# Use a imagem base do Python
FROM python:3.9

# Defina o diretório de trabalho como /app
WORKDIR /app

# Copie o arquivo requirements.txt para o diretório de trabalho
COPY requirements.txt /app
COPY balancer.py /app

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Exponha a porta 5000 para o servidor Flask
EXPOSE 5000

# Comando para executar o load_balancer.py quando o contêiner for iniciado
CMD ["python", "balancer.py"]
